import path from 'path';
import fs from 'fs';
import { useMultiFileAuthState, AuthenticationState } from '@whiskeysockets/baileys';

/**
 * Resolves the session directory dynamically to `apps/api/auth_info/{tenantId}/`
 * ensuring persistent storage per tenant across server restarts.
 */
export function getTenantAuthDir(tenantId: string): string {
  // __dirname points to `apps/api/src/services` (or `apps/api/dist/services`)
  const baseDir = path.resolve(__dirname, '../../auth_info');
  const tenantDir = path.join(baseDir, tenantId);

  if (!fs.existsSync(tenantDir)) {
    fs.mkdirSync(tenantDir, { recursive: true });
  }

  return tenantDir;
}

export interface MultiTenantAuthState {
  state: AuthenticationState;
  saveCreds: () => Promise<void>;
  authDir: string;
}

/**
 * Loads or initializes multi-file authentication state for a specific tenant.
 * Credentials persist in `apps/api/auth_info/{tenantId}/`.
 */
export async function getTenantAuthState(tenantId: string): Promise<MultiTenantAuthState> {
  const authDir = getTenantAuthDir(tenantId);
  const { state, saveCreds } = await useMultiFileAuthState(authDir);

  return {
    state,
    saveCreds,
    authDir,
  };
}

/**
 * Checks if a tenant has an existing saved session (creds.json exists).
 */
export function hasExistingSession(tenantId: string): boolean {
  const authDir = getTenantAuthDir(tenantId);
  return fs.existsSync(path.join(authDir, 'creds.json'));
}

/**
 * Removes all auth credentials for a tenant (e.g., on logout or channel deletion).
 */
export async function clearTenantAuthState(tenantId: string): Promise<void> {
  const authDir = getTenantAuthDir(tenantId);
  if (fs.existsSync(authDir)) {
    fs.rmSync(authDir, { recursive: true, force: true });
  }
}

/**
 * Lists all tenant IDs that currently have stored session directories on disk.
 */
export function listStoredTenantSessions(): string[] {
  const baseDir = path.resolve(__dirname, '../../auth_info');
  if (!fs.existsSync(baseDir)) {
    return [];
  }
  return fs
    .readdirSync(baseDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name);
}

/**
 * Resolves the true phone number from a WhatsApp JID.
 * If the JID is an internal WhatsApp LID (Linked Identity, e.g. 100051749740779@lid),
 * it queries the reverse LID mapping generated by Baileys in `auth_info/{tenantId}/lid-mapping-{lid}_reverse.json`.
 */
export function resolvePhoneNumberFromJid(tenantId: string, jid: string): string {
  if (!jid) return '';

  const cleanId = jid.replace(/@.*$/, '').replace(/:\d+$/, '');

  // 1. Standard JID: "963995433707@s.whatsapp.net"
  if (jid.includes('@s.whatsapp.net')) {
    return cleanId;
  }

  // 2. WhatsApp LID: "100051749740779@lid" or raw LID digits
  if (jid.includes('@lid') || /^\d{14,16}$/.test(cleanId)) {
    const authDir = getTenantAuthDir(tenantId);
    const reverseFile = path.join(authDir, `lid-mapping-${cleanId}_reverse.json`);
    if (fs.existsSync(reverseFile)) {
      try {
        const raw = fs.readFileSync(reverseFile, 'utf-8');
        const phone = JSON.parse(raw);
        if (phone) {
          console.log(`[WhatsAppSession] 🔄 Resolved LID ${cleanId} -> Phone ${phone}`);
          return String(phone);
        }
      } catch {}
    }
    return cleanId;
  }

  return cleanId;
}

